Unspecified changes

diff --git a/bin/task b/bin/task
--- a/bin/task
+++ b/bin/task
@@ -1,30 +1,22 @@
 #!/bin/bash
 
-ENV_BEFORE=$(env)
+. ./node_modules/task-library/src/functions
+load_vars
 
-export TASK_NAME="$1"
-export TASK_LIBRARY_ROOT="./node_modules/task-library"
-export TASK_LIBRARY_SRC="$TASK_LIBRARY_ROOT/src"
-export TASK_LIBRARY_LIB="$TASK_LIBRARY_SRC/lib"
-export TASK_LIBRARY_NODE_TASKS="$TASK_LIBRARY_SRC/node-tasks"
-export TASK_LIBRARY_TASKS="$TASK_LIBRARY_SRC/tasks"
+BOLD=$(tput bold)
+NORM=$(tput sgr0)
 
-. $TASK_LIBRARY_SRC/load-task-vars
-
-ENV_AFTER=$(env)
-
-if [ "$TASK_NAME" = "vars" ]; then
-    sort <(echo "$ENV_BEFORE" ) <(echo "$ENV_AFTER") | uniq -u
-    exit
-fi
-
+TASK_NAME="$1"
 TASK_FILE=$(taskfile $TASK_NAME)
-[ -z "$TASK_FILE" ] && echo "Task \"$TASK_NAME\" not found." && exit 1
+[ -z "$TASK_FILE" ] && echo -e "Task ${BOLD}$TASK_NAME${NORM} not found" && exit 1
 chmod +x "$TASK_FILE"
-echo "⚡️ Task \"$TASK_NAME\" started. Source: $TASK_FILE"
-START=$(nowInMs)
+echo -e "${NORM}⚡️ Task ${BOLD}$TASK_NAME${NORM} started" # Source: $TASK_FILE"
+TIME_BEFORE=$(now)
 "$TASK_FILE" "${@:2}"
 EXIT_CODE=$?
-END=$(nowInMs)
-echo "🏁 Task \"$TASK_NAME\" completed with exit code $EXIT_CODE in $((END-START)) ms."
+TIME_AFTER=$(now)
+TIME_TAKEN_MS=$((TIME_AFTER-TIME_BEFORE))
+TIME_TAKEN_S=$(echo "scale=1;${TIME_TAKEN_MS}/1000" | bc)
+[[ $TIME_TAKEN_S == .* ]] && TIME_TAKEN_S="0$TIME_TAKEN_S"
+echo -e "${NORM}🏁 Task ${BOLD}$TASK_NAME${NORM} completed with exit code $EXIT_CODE in ${TIME_TAKEN_MS}ms (${TIME_TAKEN_S}s)"
 exit $EXIT_CODE
