Unspecified changes

diff --git a/src/tasks/deploy b/src/tasks/deploy
--- a/src/tasks/deploy
+++ b/src/tasks/deploy
@@ -1,6 +1,15 @@
 #!/bin/bash
 
-[ "$1" != "$STAGE" ] && load_vars "$1"
+[ ! -z "$1" ] && [ "$1" != "$STAGE" ] && load_vars "$1"
+
+read -p "❓ Are you sure? " choice
+case "$choice" in 
+  y|Y ) ;;
+  n|N ) echo "⚠️  Aborting..."; exit 0;;
+  * ) echo "⚠️  Invalid input"; exit 1;;
+esac
+
+echo
 
 [ $(is_on_npm) = "true" ] && npx task publish
 
@@ -8,4 +17,4 @@
 
 [ $(is_on_sls) = "true" ] && sls deploy
 
-(exit 0)
+exit 0
